### ISSUE TITLE
Code not compiling

### ISSUE THREAD

**Issue by gautamverma40** [smitshilu/FASTAlgorithm#1]
I cannot find AbstractFASTClusterer class in the project

**Comment by smitshilu** [comment]
This is a plugin for Weka tool, AbstractFASTClusterer will be added from Weka files

**Comment by gautamverma40** [comment]
But I didn't find  AbstractFASTClusterer class in weka.jar

On Jul 28, 2017 5:07 PM, "Smit Shilu" <notifications@github.com> wrote:

Closed #1 <https://github.com/smitshilu/FASTAlgorithm/issues/1>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/smitshilu/FASTAlgorithm/issues/1#event-1183371492>, or mute
the thread
